### ISSUE TITLE
distance.vincenty Error

### ISSUE THREAD

**Issue by Hasan-ta** [mapillary/map_matching#4]
I was trying to run the example script as follows:
```
~/Desktop/map_matching-master/examples$ python2 map_matcher.py "host=localhost port=5432 dbname=gis user=postgres password=xxxxx" berlin_ways < sequence_in_berlin.txt
```

I received the following error:

```
Traceback (most recent call last):
  File "map_matcher.py", line 232, in <module>
    sys.exit(main(sys.argv[1:]))
  File "map_matcher.py", line 216, in main
    candidates = map_match(conn, road_table_name, sequence, search_radius, max_route_distance)
  File "map_matcher.py", line 190, in map_match
    return list(matcher.offline_match(candidates))
  File "/usr/local/lib/python2.7/dist-packages/map_matching-0.1-py2.7.egg/map_matching/map_matching.py", line 182, in offline_match
    winners = list(self.offline_search(candidates))
  File "/usr/local/lib/python2.7/dist-packages/map_matching-0.1-py2.7.egg/map_matching/viterbi_path.py", line 244, in offline_search
    for winner, scanned_candidates, new_start in self.search_winners(states):
  File "/usr/local/lib/python2.7/dist-packages/map_matching-0.1-py2.7.egg/map_matching/viterbi_path.py", line 217, in search_winners
    candidate.body, [c.body for c in next_state])
  File "/usr/local/lib/python2.7/dist-packages/map_matching-0.1-py2.7.egg/map_matching/map_matching.py", line 153, in calculate_transition_costs
    great_circle_distance = distance.vincenty(
AttributeError: 'module' object has no attribute 'vincenty'
```

Any idea about the source of this error?

Thank you.

**Comment by ptpt** [comment]
With the latest `geopy`, the module `geopy.distance` has this attribute. Can you ensure the `geopy` package is updated?

```
pip install -U geopy
```

**Comment by Hasan-ta** [comment]
Yeah I did that before, but didn't work.
I used vincenty function directly by adding the following line:
`from geopy.distance import vincenty`
and changing the line:
`great_circle_distance = distance.vincenty((source.measurement.lat, source.measurement.lon),(target_measurement.lat, target_measurement.lon)).meters`
to:
`great_circle_distance = vincenty((source.measurement.lat, source.measurement.lon),(target_measurement.lat, target_measurement.lon)).meters`

and for some reason this worked for the example data set provided.

**Comment by ptpt** [comment]
Thanks @Hasan-ta I hope it is fixed.
